server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /token {
        proxy_pass http://security:3000/v1/token;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /upload {
        auth_request /auth;
        proxy_pass http://uploader:3000/v1/upload;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /images/ {
        proxy_pass http://storage:9000/data/;
        proxy_set_header Host $host;
    }

    location = /auth {
        internal;
        proxy_pass http://security:3000/v1/token/validation;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        return 404;
    }
}
